name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  merge_group:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  quality:
    name: Public Quality
    uses: MNPPI/.github/.github/workflows/public-quality.yml@26458dfcdff444d58fbe471fe45be48679b57c88
    with:
      profile: python
